### ISSUE TITLE
Behavior when chips are selected.

### ISSUE THREAD

**Issue by muric-dev** [vbalagovic/flutter_simple_multiselect#2]
I don't know if it's the expected behavior of this, when you select one or more items, and you unFocus the widget, the hint and TextInput disappears, this is annoying and confusing for the user doesn't have an input.

<img  width="250"   src="https://i.ibb.co/SN2NjgL/IMG-1251.jpg">

**Comment by vbalagovic** [comment]
Hi, thanks for the input :) but this is expected behavior, regarding the UX/UI I wanted it to be like vue multi-select, that everything is basically "one input" that is what differs this package from the others and the reason I 've created it :)
